module.exports = {
  apps: [
    {
      name: 'app',
      script: 'build/src/index.js',
      instances: process.env.APP_INSTANCES || 1,
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      time: true,
      max_memory_restart: '1G',
      node_args: '--max-old-space-size=1024',
      env: {
        NODE_ENV: process.env.NODE_ENV || 'development',
      },
      error_file: './logs/app-error.log',
      out_file: './logs/app-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm Z',
    },
    {
      name: 'worker',
      script: 'build/src/shared/workers/worker-runner.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      time: true,
      max_memory_restart: '1G',
      node_args: '--max-old-space-size=1024',
      env: {
        NODE_ENV: process.env.NODE_ENV || 'development',
      },
      error_file: './logs/worker-error.log',
      out_file: './logs/worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm Z',
    },
    {
      name: 'cron-jobs',
      script: 'build/src/shared/cron/cron-runner.js',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      time: true,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: process.env.NODE_ENV || 'production',
      },
      error_file: './logs/cron-error.log',
      out_file: './logs/cron-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm Z',
    },
  ],
};
