export type Permission =
  | 'viewProfile'
  | 'updateProfile'
  | 'viewPosts'
  | 'createPost'
  | 'updateOwnPost'
  | 'deleteOwnPost'
  | 'createComment'
  | 'updateOwnComment'
  | 'deleteOwnComment'
  | 'viewNotifications'
  | 'moderatePosts'
  | 'moderateComments'
  | 'viewAllUsers'
  | 'manageUsers'
  | 'manageRoles'
  | 'viewSystemAnalytics'
  | 'viewAuditLogs';
